Server:
  RunMode: release
  HttpPort: 5023
  ReadTimeOut: 3
  WriteTimeOut: 5

APP:
  AppName: blog_gin
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  MaxLogFileSize: 50
  MaxLogBackUp: 15
  LogLevel: info
  LogPrefix: blog_log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:5023/static
  UploadImageMaxSize: 5 #MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
  DefaultContextTimeout: 2

Database:
  DBType: mysql
  UserName: spider
  Passwd: 'MYSQL@5.7.38$com!'
  Host: c1:5555
  DBName: dev_go
  ConTimeOut: 2s
  TablePrefix: blog
  Charset: utf8mb4
  ParseTime: true
  MaxIdleCons: 10
  MaxOpenCons: 30

JWT:
  Secret: spider
  Issuer: go-tour
  Expire: 7200

Email:
  Host: smtp.126.com
  Port: 465
  UserName: lgc523@126.com
  Password: IZLJEAVNWKBXXLXK
  IsSSL: true
  From: lgc523@126.com
  To:
    - spider.nns@gmail.com

DingTalk:
  Url: https://oapi.dingtalk.com/robot/send?access_token=
  To:
    #  prod
    - 3261267c1b732e553908306695b7602dcd62180f6d3165b945509a29a825e979
    #  dev
    - 5b3c64935993c5048c57e1b02c0dcec0ae440ec00454145c3eb8cc02127f9556