Server:
  RunMode: debug
  HttpPort: 5023
  ReadTimeOut: 3
  WriteTimeOut: 5

APP:
  AppName: blog_gin
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  LogPrefix: blog_log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:5023/static
  UploadImageMaxSize: 5 #MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png

Database:
  DBType: mysql
  UserName: spider
  Passwd: 'MYSQL@5.7.38$com!'
  Host: c1:5555
  DBName: dev_go
  ConTimeOut: 2s
  TablePrefix: blog
  Charset: utf8mb4
  ParseTime: true
  MaxIdleCons: 10
  MaxOpenCons: 30

JWT:
  Secret: spider
  Issuer: go-tour
  Expire: 7200